##### Instalando o TensorFlow 2.0

#### Etapa 2: Importando as bibliotecas e a base de dados

In [1]:
import numpy as np
import datetime
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

In [2]:
tf.__version__

'2.14.0'

#### Etapa de Pre-Processamento

In [4]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

4422102/4422102 [==============================] - 1s 0us/step


In [5]:
X_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [6]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,
          1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
          0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,
          0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,
          0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,
         10,   0],
       [  

In [7]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [9]:
y_train[0]

9

#### Normalizando as imagens

Dividimos cada pixel das imagens das bases de treinamento e teste, utilizando o maior valor que é 255.

Com isso, cada pixel estará na faixa entre 0 e 1. Dessa forma, a rede neural vai treinar mais rápid

In [10]:
X_train = X_train / 255.0


In [11]:
X_test = X_test / 255.0

In [12]:
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

#### Remodelando (reshaping) a base de dados

Como estamos trabalhando com uma rede neural densa, mudamos a dimensão das bases de dadps para ficarem em formato de vetor

In [14]:
X_train.shape

(60000, 784)

In [13]:
X_train = X_train.reshape(-1, 28*28)

In [15]:
X_train.shape

(60000, 784)

In [16]:
# Mudamos também a dimensão da base de teste
X_test = X_test.reshape(-1, 28*28)

In [17]:
X_test.shape

(10000, 784)

#### Etapa 4: Construindo a Rede Neural Artificial

##### Definindo o modelo
Definimos um objeto do tipo Sequencial (Sequencia de camadas)

In [18]:
model = tf.keras.models.Sequential()

In [19]:
model

##### Adicionando a primeira camada densa (fully-connected)
Hyper-parametros de camada:

umeros de units/neuronios: 128
funcão de ativação: ReLU
input_shape (camada de entrada): (784,)


In [22]:
model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784, )))

#### Adicionando Dropout

Dropout é uma tecnica de regularização naqual alguns neuronios da camada tem seu valor mudado para zero, ou seja, durante o treinamento esses neuronios não serão atualizados. Com isso, temos menos chances de ocorrer overfitting

In [21]:
model.add(tf.keras.layers.Dropout(0.2))

#### Adicionando a camada de saída

units: numeros de classes (10 na base de dados Fashion MNIST)

Função de ativação: Softmax

In [23]:
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

#### Copilando o modelo
optimazer(otimizador): Adam

Loss(função de erro): Sparse softmax (categorical) crossentropy

In [28]:
model.compile(optimizer = 'adam', loss='sparse_categorical_crossentropy', metrics= ['sparse_categorical_accuracy'])

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 128)               16512     
                                                                 
 dense_2 (Dense)             (None, 10)                1290      
                                                                 
Total params: 118282 (462.04 KB)
Trainable params: 118282 (462.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


#### Treinando o modelo

In [30]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 15s 6ms/step - loss: 0.5260 - sparse_categorical_accuracy: 0.8095
Epoch 2/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.4040 - sparse_categorical_accuracy: 0.8530
Epoch 3/5
1875/1875 [==============================] - 15s 8ms/step - loss: 0.3685 - sparse_categorical_accuracy: 0.8665
Epoch 4/5
1875/1875 [==============================] - 15s 8ms/step - loss: 0.3513 - sparse_categorical_accuracy: 0.8709
Epoch 5/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.3367 - sparse_categorical_accuracy: 0.8747


#### Avaliação do modelo

In [31]:
test_loss, test_acuraccy = model.evaluate(X_test, y_test)

313/313 [==============================] - 2s 4ms/step - loss: 0.3610 - sparse_categorical_accuracy: 0.8698


In [32]:
print("Test accuracy: {}".format(test_acuraccy))

Test accuracy: 0.8697999715805054


In [33]:
test_loss

0.3610486090183258

Tarefa
Olá,

O desafio dessa tarefa é aumentar  a precisão da rede neural e o objetivo é conseguir mais do que 87% de precisão na base de dados de teste. Abaixo algumas sugestões de melhoria:

Treinar a rede neural por mais épocas

Adicionar mais camadas escondidas

Trocar o otimizador e a taxa de aprendizagem (learning rate)

Trocar as funções de ativação

Na próxima aula você terá a solução!

Bom trabalho!

Jones, Hadelin & Kirill

#### solução do exercicio
Estamos definindo quatro camadas ocultas

In [2]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

In [3]:
X_train = X_train / 255.0

In [4]:
X_test = X_test / 255.0

In [5]:
X_train = X_train.reshape(-1, 28*28)

In [6]:
X_train.shape

(60000, 784)

In [ ]:
X_test = X_test.reshape(-1, 28*28)

In [34]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784, )))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(units=128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(units=128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(units=128, activation='relu'))
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

In [35]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [36]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 128)               100480    
                                                                 
 dropout_1 (Dropout)         (None, 128)               0         
                                                                 
 dense_4 (Dense)             (None, 128)               16512     
                                                                 
 dropout_2 (Dropout)         (None, 128)               0         
                                                                 
 dense_5 (Dense)             (None, 128)               16512     
                                                                 
 dropout_3 (Dropout)         (None, 128)               0         
                                                                 
 dense_6 (Dense)             (None, 128)              

In [37]:
model.fit(X_train, y_train, epochs=20)

Epoch 1/20
1875/1875 [==============================] - 15s 7ms/step - loss: 0.5918 - sparse_categorical_accuracy: 0.7865
Epoch 2/20
1875/1875 [==============================] - 13s 7ms/step - loss: 0.4446 - sparse_categorical_accuracy: 0.8403
Epoch 3/20
1875/1875 [==============================] - 13s 7ms/step - loss: 0.4074 - sparse_categorical_accuracy: 0.8543
Epoch 4/20
1875/1875 [==============================] - 13s 7ms/step - loss: 0.3835 - sparse_categorical_accuracy: 0.8624
Epoch 5/20
1875/1875 [==============================] - 13s 7ms/step - loss: 0.3673 - sparse_categorical_accuracy: 0.8677
Epoch 6/20
1875/1875 [==============================] - 13s 7ms/step - loss: 0.3545 - sparse_categorical_accuracy: 0.8716
Epoch 7/20
1875/1875 [==============================] - 13s 7ms/step - loss: 0.3465 - sparse_categorical_accuracy: 0.8737
Epoch 8/20
1875/1875 [==============================] - 13s 7ms/step - loss: 0.3362 - sparse_categorical_accuracy: 0.8783
Epoch 9/20
1875/1875 [==

In [38]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

313/313 [==============================] - 2s 6ms/step - loss: 0.3281 - sparse_categorical_accuracy: 0.8861


In [39]:
print("Test accuracy: {}".format(test_accuracy))

Test accuracy: 0.8860999941825867


#### Salvando o modelo

In [40]:
model_json = model.to_json()
with open("fashion_model.json", "w") as json_file:
    json_file.write(model_json)

##### Salvando os pesos

In [ ]:
model.save_weights("fashion_model.h5")